name: Deploy

on:
  push:
    branches:
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy QA
        if: github.ref == 'refs/heads/qa'
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            cd ~/apps/demo-app &&
            git pull origin qa &&
            docker compose up -d --build qa
          '

      - name: Deploy Prod
        if: github.ref == 'refs/heads/main'
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            cd ~/apps/demo-app &&
            git pull origin main &&
            docker compose up -d --build prod
          '
